### ISSUE TITLE
SyntaxError: invalid syntax; Error at Line 26

### ISSUE THREAD

**Issue by hdfc394** [Jeyaprabu/Unacademy-Downloader#5]
![capture](https://user-images.githubusercontent.com/30144237/28159159-aec8ea50-67d9-11e7-836f-2bd382db04a1.PNG)

**Comment by Jeyaprabu** [comment]
Hi,
I can't completely understand why this happens.
Can you try from default command line rather than Ipython console.
I suspect the issue is due to Ipython interpretation

**Comment by hdfc394** [comment]
I also tried with Command Prompt.....The same issue is shown previously.And same now with Spyder......

**Comment by Jeyaprabu** [comment]
Hi,
I tried with the same code (downloaded and tested), it is working fine
make sure you do following things
1. Download the Source file completely, don't copy paste the code in the editor. Because that may cause indentation errors (Most probably your are facing this error)
2. All the dependencies are available. (For eg. Beautiful Soup package)

**Comment by hdfc394** [comment]
Sorry for my late reply......I am getting same error what i mentioned before even when i tried to execute it from cmd..... I don't know what's wrong from my side.Maybe you could please guide me on this and i am also a novice. So i am having Python 3.6 installed on my Laptop with beautifulsoup4 is installed on it. As you mentioned in instructions to make sure of urllib...I don't know how to install it seperately. With these things in place i tried your script by opening "Unac_down_main.py" through cmd. The execution gives this message:
"
C:\Unacademy-Downloader-master>Unac_down_main.py
  File "C:\Unacademy-Downloader-master\Unac_down_main.py", line 29
    print "\nDownloaded Audio ", lesson_name, " -", (int(ret.headers["Content-Length"])/1024), "KB"
                              ^
SyntaxError: invalid syntax
"

So can you guide me through this. By the way i want to mention for your previous reply of 1st point that i never copy-pasted code instead i opened "Unac_down_main.py" file using spyder in Anaconda, now also i tried it on Spyder along with cmd, both are showing same errors as mentioned above.

**Comment by Jeyaprabu** [comment]
Hi,
Thanks for making it clear. 
1. The issue is due to Python 3.6 because print statements are expected to have parenthesis in python 3.x
2. Either You have to run this script on Python 2.7 or u can try adding parenthesis to the print statements and try it on Python 3.6
Please refer https://stackoverflow.com/questions/937491/invalid-syntax-when-using-print

If u still seeing problems, let me know

**Comment by hdfc394** [comment]
Thanks for your response.....

1.Yes paranthesis should be added to all print statements of code if we use Python 3.x 
Reference: https://stackoverflow.com/questions/937491/invalid-syntax-when-using-print

2.Also you should change "raw_input" to "input" for smooth execution of code in Python 3.x
Reference: https://stackoverflow.com/questions/954834/how-do-i-use-raw-input-in-python-3

I think its better if you add these two points to README.md. This will make other users life simple if they don't have knowledge in programming.

And once again Thanks for your Script and Thanks for your time in responding to my errors.
